poster.pdf: poster.tex beamerthemeRJH.sty
	pdflatex -shell-escape poster

method_image: method_image.tex beamerthemeRJH.sty
	pdflatex -shell-escape method_image

clean:
	rm -f *.log *.out *.aux *.bbl *.blg *.nav *.snm *.toc poster.pdf poster-pics.pdf 
